### PR TITLE
Added setup instructions with detailed screenshots

### PR DESCRIPTION
**Pull request by ankushdharkar**
This will help in setting up the package for new users

### CODE REVIEW

**Comment by whitequark** [comment]
Thanks!

**Comment by EvilJordan** [comment]
This is awesome! What would be the reason when I search for rainbowth in the Install Package prompt, nothing shows up?

**Comment by whitequark** [comment]
Already installed?

**Comment by EvilJordan** [comment]
I got nothin' :-/

screen shot 2018-02-14 at 10 49 00 pm

**Comment by ankushdharkar** [comment]
@EvilJordan In the command palette, try `Remove Package` and remove the Rainbowth package

Then reinstall Rainbowth using `Install Package` command

**Comment by EvilJordan** [comment]
That did it. Thank you!!

**Comment by ankushdharkar** [comment]
You're welcome. Glad that it's finally working for you too ☺️

**Pull request merged**
